### ISSUE TITLE
1 .求问这个本地代理的意义是什么？ 2. Firefox不适配，搜索无响应。

### ISSUE THREAD

**Issue by joseph-cheung** [zaxtyson/AnimeSearcher#1]
既然获取了真实地址，直接上Dplayer不可以吗？不是很明白。
以及Firefox不适配，搜索无响应。

**Comment by zaxtyson** [comment]
是这样的，即便获取了视频直链，但是有些视频仍然不能直接播放。比如 m3u8 视频文件中视频资源使用的是相对地址，我们需要处理后再返回给 Dplayer，还有跨域播放失败，防盗链限制等问题，这些情况 Dplayer 都没办法处理。😀请试试 Chrome 或者 Edge，如果开始搜索，控制台会显示 debug 信息的~另外，release并不是最新的，建议 clone

**Comment by zaxtyson** [comment]
Android 的话，确实不好移植。这个之前没打算做成 web 服务，当然也是可以改的，这个本来就是打算本地用，搞成 web 的话，人多了怕凉得快(有些引擎还是抓了人家 APP 的包，甚至还做了逆向)😜
