### ISSUE TITLE
一个小小的建议

### ISSUE THREAD

**Issue by Huzerovo** [zaxtyson/AnimeSearcher#1]
建议开头加上
#!/bin/python
或者其他更好的写法

不然可能会当成 shell 脚本运行。。。

**Comment by Huzerovo** [comment]
另外当前 ( 0.9.9 ) 的源码里 web 文件夹里的 js 文件夹好像没有上传到。。。

**Comment by lozyue** [comment]
> 
> 
> 另外当前 ( 0.9.9 ) 的源码里 web 文件夹里的 js 文件夹好像没有上传到。。。

@zaxtyson  大意了啊
不过现在你可以去web分支下载更新的打包版本。

**Comment by zaxtyson** [comment]
我一定耗子尾汁, 已经更新到 `v.1.0.0` , js 补上了

关于 `shebang` , 一般是写 `#!/usr/bin/env python3`, 因为一般 linux 上面可能存在多个python版本, 包括一个用于兼容考虑的 python2, 自带的 python3.6(Ubuntu20改用了 3.8), 用户还可能安装其它版本. 因为自带的版本可能过低, 但是也不能直接卸载, 很可能导致系统其它依赖出现问题. 因为我也不知道用户的环境, 所以还不如让用户手动 `python3.x run.py`

关于 `shebang` 的讨论见: https://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my

**Comment by Huzerovo** [comment]
> 我一定耗子尾汁, 已经更新到 `v.1.0.0` , js 补上了
> 
> 关于 `shebang` , 一般是写 `#!/usr/bin/env python3`, 因为一般 linux 上面可能存在多个python版本, 包括一个用于兼容考虑的 python2, 自带的 python3.6(Ubuntu20改用了 3.8), 用户还可能安装其它版本. 因为自带的版本可能过低, 但是也不能直接卸载, 很可能导致系统其它依赖出现问题. 因为我也不知道用户的环境, 所以还不如让用户手动 `python3.x run.py`
> 
> 关于 `shebang` 的讨论见: https://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my

又学到一些不知道的知识，其实我学 linux 还没多久，多谢大佬指点
