### ISSUE TITLE
FreeBSD上出现错误

### ISSUE THREAD

**Issue by clean-master** [zaxtyson/AnimeSearcher#10]
在运行python3.8 -m pip install -r requirements.txt后出现。
用3.7和3.9出现同样问题，似乎是说没有这个版本？
![IMG_20210313_213329](https://user-images.githubusercontent.com/37928663/111035184-366a7d80-8454-11eb-8183-90dcd972d978.jpg)

**Comment by zaxtyson** [comment]
可能是你使用的 pip 源没有这个`0.9.0` 的包, 可以直接 `python3.8 -m pip install Pympler` 安装试试, 看看能不能用.

可以参考一下他们的 GitHub: https://github.com/pympler/pympler

**Comment by clean-master** [comment]
已解决，参考https://forums.freebsd.org/threads/python-undefined-symbol-close_range-fbsd_1-6.78983/#post-495243，未更新至系统最新版本的问题。

**Comment by zaxtyson** [comment]
good job😃
