### ISSUE TITLE
能不能添加  本地弹幕   功能

### ISSUE THREAD

**Issue by be4r6h** [zaxtyson/AnimeSearcher#11]

**Comment by zaxtyson** [comment]
可以倒是可以, 不过前端这部分是 @lozyue 负责的,他最近可能也没什么时间哈哈

**Comment by lozyue** [comment]
> 
> 
> 可以倒是可以, 不过前端这部分是 @lozyue 负责的,他最近可能也没什么时间哈哈

可以的，目前要实现并且具有良好体验的话，绝对是要后端动态支持的。以后会考虑，特别是如果上 electron 的话

**Comment by lozyue** [comment]
目前已经提供本地弹幕支持，作为可选功能实现在[AnimeUI v2.x Fantasy主题风格](https://github.com/lozyue/AnimeSearcherUI/tree/webui/AnimeUI/themes/styles/fantasy)中， 完整程序最先在[AnimeUI webui分支](https://github.com/lozyue/AnimeSearcherUI/tree/webui)提供预览，后续会正式发布在 AnimeUI v2.0-alpha3 中。

> 未来可预计的一段时间内没有打包作为electron应用的打算了
