### ISSUE TITLE
zzzfun版本过低，无法播放

### ISSUE THREAD

**Issue by zsbai** [zaxtyson/AnimeSearcher#13]

**Comment by zaxtyson** [comment]
已经发现了, 还有其它几个引擎它们也有些更新, 都修复好了。还在解决弹幕的一些问题, 搞定了咋们就更新😁

**Comment by zsbai** [comment]
辛苦啦，作者有博客之类的么？

**Comment by zaxtyson** [comment]
有的,不过没时间写东西哈哈 https://zaxtyson.cn

**Comment by zsbai** [comment]
想找一下大佬的赞赏码...不过没找到emmmm，如果愿意的话可以留一下赞赏码赞助杯奶茶喝，辛苦啦

**Comment by zaxtyson** [comment]
用爱发电~

**Comment by zaxtyson** [comment]
已经修复, 见 `v1.4.1`

**Comment by zsbai** [comment]
感谢！已经可以正常了
