### ISSUE TITLE
电视直播问题

### ISSUE THREAD

**Issue by BakaDream** [zaxtyson/AnimeSearcher#20]
现在的源不能正常播放

**Comment by zaxtyson** [comment]
hh, 还真有兄弟在看电视啊, 那个源是北邮的, 看还是能看的, 可能要等一等, 速度不是很快

**Comment by nymanyim** [comment]
@zaxtyson 大大，CCTV5跨域错误，加了允许没用啊，是源失效了还是咋的，输出如下
![image](https://user-images.githubusercontent.com/54471703/127741707-186c225b-7199-438e-a0a7-f3ebb66d4c3f.png)

**Comment by nymanyim** [comment]
还真是失效了，资源显示404了

**Comment by BakaDream** [comment]
北邮的源维护了
