### ISSUE TITLE
HTTPS问题

### ISSUE THREAD

**Issue by yuanzhidao** [zaxtyson/AnimeSearcher#25]
我将此项目部署到了我的服务器上并配置了SSL证书开启了HTTPS
但该项目有些资源是http协议 会被blocked
麻烦修复谢谢

**Comment by zaxtyson** [comment]
以前本着节省带宽的原则没有强制 API 代理所有流量，图片根本没有代理(现在因为跨域问题导致服务器端部分图片无法加载)，视频只有必要时才走代理。

如果你是`主域名:6001`去访问这个服务，浏览器可能自动给你跳到 https 去，单独开一个子域名，不配置证书即可。
 
如果你的需求是，接口返回的所有流量通过 HTTPS 传输，那么为 API 的 6001 端口设置一个反向代理，同时配置好证书。在配置文件中强制所有流量通过 API 代理，这样所有第三方资源都是通过反向代理返回，保证链接都是 HTTPS。

https://github.com/zaxtyson/Anime-API/blob/dev/config.py
