### ISSUE TITLE
请问 为什么访问不了index.html

### ISSUE THREAD

**Issue by pytwj** [zaxtyson/AnimeSearcher#30]
![image](https://user-images.githubusercontent.com/62314967/147388544-d2722802-896e-479b-91f1-08d97ad3a134.png)

**Comment by lozyue** [comment]
1.x的WebUI直接从本地打开的方式，和Server是分离的。服务端默认也没有做静态资源代理。

**Comment by lozyue** [comment]
WebUI的v2.0-alpha0版本可以在本仓库的[Git-Page](https://zaxtyson.github.io/AnimeSearcher/)中预览。
现在可以直接使用git-page的WebUI配合本地服务端使用，无需使用额外部署或本地文件协议的运行方式。 

目前请使用这个分支作为server端以配合新版UI: [AnimeSearcher/tree/add-storage](https://github.com/zaxtyson/AnimeSearcher/tree/add-storage)
如果要自行部署，请到[AnimeSearcherUI/tree/webui](https://github.com/lozyue/AnimeSearcherUI/tree/webui)核查最新版本

虽然图中的问题应该是网站部署时部署路径或访问路径之一错误的问题（之前没看清...💫）
