### ISSUE TITLE
[question] 本项目用pyinstaller打包的exe在virustotal上居然是全绿，是怎么做到的？

### ISSUE THREAD

**Issue by mo-han** [zaxtyson/AnimeSearcher#35]
【更新】
解压出来单独把exe上传扫描后发现也是有4个“阳性”结果的，那没事了~

---

新版本pyinstaller一般会一片红，因为太新，大量杀软无脑误报。
旧版本的好得多，但一般也会有几个误报记录。
但是这里发布的exe却无一误报，这是怎么做到的，还望赐教！

**Comment by zaxtyson** [comment]
可能是 upx 压缩了一把
