### ISSUE TITLE
linux下报错

### ISSUE THREAD

**Issue by mokurin000** [zaxtyson/AnimeSearcher#6]
```
Traceback (most recent call last):
  File "ui.pyw", line 45, in <module>
    ui = SimpleUI()
  File "ui.pyw", line 17, in __init__
    self.init_ui()
  File "ui.pyw", line 22, in init_ui
    self.ui.wm_iconbitmap(f"{PATH}/logo.ico")
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2071, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "/home/poly/AnimeSearcher/logo.ico" not defined
```

已经安装好依赖包 python: 3.8

**Comment by zaxtyson** [comment]
刚才修复了一点问题, 请重新 clone 一下

```
"/home/poly/AnimeSearcher/logo.ico" not defined
```

这是logo文件丢了, 检查一下这个文件是不是还在

另外, 新年快乐啊~~

**Comment by mokurin000** [comment]
> 刚才修复了一点问题, 请重新 clone 一下
> 
> ```
> "/home/poly/AnimeSearcher/logo.ico" not defined
> ```
> 
> 这是logo文件丢了, 检查一下这个文件是不是还在
> 
> 另外, 新年快乐啊~~

文件还在啊…… 还是这个错误
新年快乐！
不过手动从浏览器打开web界面了（

![图片](https://user-images.githubusercontent.com/34085039/107641216-4b65bc80-6cae-11eb-8057-01554d2040bb.png)

是不是tk的锅？？？ （不懂python）

**Comment by zaxtyson** [comment]
的确是tk的锅，位图格式不一样，linux下面不兼容。而且有一个更加严重的问题：linux下面 asyncio 的事件循环只能在main thread里面跑，我去看看先。其实 `ui.pyw` 只是方便用浏览器打开 `web/index.html`，没有其他用途。运行 `app.py` 再用浏览器打开网页就行，UI 只是静态的页面。

**Comment by mokurin000** [comment]
> 的确是tk的锅，位图格式不一样，linux下面不兼容。而且有一个更加严重的问题：linux下面 asyncio 的事件循环只能在main thread里面跑，我去看看先。其实 `ui.pyw` 只是方便用浏览器打开 `web/index.html`，没有其他用途。运行 `app.py` 再用浏览器打开网页就行，UI 只是静态的页面。

…… Termux无法运行也是这个原因吗？
