### ISSUE TITLE
弹幕显示问题（有图）

### ISSUE THREAD

**Issue by XIANJo** [zaxtyson/AnimeSearcher#9]
观看2小时以上长度的影片，弹幕列表显示弹幕到1:59:52后就没了，之后的弹幕似乎无法显示。(弹幕源是b站)

**Comment by lozyue** [comment]
看来显示没有问题，但你这个标题成功把我吸引过来了

**Comment by zaxtyson** [comment]
好像是哔哩哔哩弹幕接口的问题, 我去康康

**Comment by XIANJo** [comment]
> 看來顯示沒有問題，但你這個標題成功把我吸引過來了
![擷取0](https://user-images.githubusercontent.com/63054834/111036066-4e440080-8458-11eb-9cb2-4ae0aa953013.jpg)



会变成这样
过了1:59:52之后就没有弹幕了

**Comment by zaxtyson** [comment]
bilibili 之前的接口只能拿到 120 分钟的弹幕, 新的接口改为分段传输 `proto` 数据, 正在改~

**Comment by zaxtyson** [comment]
已修复 😁

![image](https://user-images.githubusercontent.com/20383074/111059209-b1707a00-84ce-11eb-8897-c775b3b8318a.png)

![image](https://user-images.githubusercontent.com/20383074/111059241-ee3c7100-84ce-11eb-8023-961c0a446a06.png)

**Comment by XIANJo** [comment]
> 已修復 😁
> 
> ![圖像](https://user-images.githubusercontent.com/20383074/111059209-b1707a00-84ce-11eb-8897-c775b3b8318a.png)
> 
> ![圖像](https://user-images.githubusercontent.com/20383074/111059241-ee3c7100-84ce-11eb-8023-961c0a446a06.png)

**Comment by XIANJo** [comment]
谢谢 😁
所以只要等下一次更新就好了是吗？

**Comment by zaxtyson** [comment]
对, 加了不少东西, 在稍微等一下, 我测试没问题很快就可以发 下一个版本了😆
